

TOOLCHAIN_PATH   = 
TOOLCHAIN_PREFIX = 

CC               = $(TOOLCHAIN_PATH)$(TOOLCHAIN_PREFIX)gcc

LIB              = kronos
LIB_VERSION      = 1.0
LIB_NAME         = lib$(LIB)-$(LIB_VERSION).so
SOFT_NAME        = lib$(LIB).so
LIB_DIR          = ./build/lib
ENV_DIR          = ./build/env
TEST_DIR         = ./build/test

CFLAGS = -fno-common -Wall

ROOTFS           = ../../rootfs
